name: 拉取镜像推送

on:
  workflow_dispatch:   # 手动触发即可，不需要定时

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 登录阿里云仓库
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            crpi-itqf3iw9kew7jxxr.cn-shenzhen.personal.cr.aliyuncs.com \
            -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: 拉取官方镜像（v0.5.4）
        run: |
          docker pull chrischoy/minkowski_engine:v0.5.4

      - name: 重新打 tag（改成 latest 并推送到阿里云）
        run: |
          docker tag chrischoy/minkowski_engine:v0.5.4 \
            crpi-itqf3iw9kew7jxxr.cn-shenzhen.personal.cr.aliyuncs.com/minkowski/minkowski_engine:latest
          docker push crpi-itqf3iw9kew7jxxr.cn-shenzhen.personal.cr.aliyuncs.com/minkowski/minkowski_engine:latest
