name: 拉取镜像推送

on:
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
        description: '原镜像名称:版本'
        required: true
        default: ''docker.io/chrischoy/minkowski_engine:v0.5.4''
      NEW_NAME:
        description: '同步后镜像名称:版本'
        required: true
        default: 'latest'
      TARGET_REGISTRY:
        description: '仓库地址'
        required: true
        default: 'crpi-itqf3iw9kew7jxxr.cn-shenzhen.personal.cr.aliyuncs.com'
      TARGET_REPOSITORY:
        description: '命名空间'
        required: true
        default: 'minkowski'
      TARGET_DOCKRE_REGISTRY:
        description: '镜像仓库'
        required: true
        default: 'minkowski'
      ARCH:
        description: '系统架构'
        required: true
        default: 'amd64'
        type: choice
        options:
          - amd64
          - arm64
          - arm/v7
          - arm/v6
          - 386
          - s390x
          - ppc64le

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
            - name: 登录到 Docker 仓库
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ github.event.inputs.TARGET_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        continue-on-error: true

      - name: 检查 Docker 登录成功
        if: ${{ steps.login.outcome == 'success' }}
        run: echo "Docker 登录成功"

      - name: 检查 Docker 登录失败
        if: ${{ steps.login.outcome != 'success' }}
        run: echo "Docker 登录失败"

- name: 拉取、标记并推送
  run: |
    docker pull --platform linux/amd64 chrischoy/minkowski_engine:v0.5.4
    docker tag chrischoy/minkowski_engine:v0.5.4 \
      ${{ secrets.REGISTRY }}/minkowski/minkowski_engine:v0.5.4
    docker push ${{ secrets.REGISTRY }}/minkowski/minkowski_engine:v0.5.4
        # continue-on-error: true

      - name: 检查镜像推送成功
        if: ${{ steps.pull_tag_push.outcome == 'success' }}
        run: echo "Docker 镜像推送成功"

      - name: 检查镜像推送失败
        if: ${{ steps.pull_tag_push.outcome != 'success' }}
        run: echo "Docker 镜像推送失败"
